# Generated by Django 5.2.8 on 2025-12-01 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp3', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='Fname',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='Lname',
            new_name='lname',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='Phone',
            new_name='phone',
        ),
    ]
